class Stock
  attr_reader :symbol, :ask, :avg_daily_vol, :bid, :ask_real_time, :bid_real_time, :book_value, :change_percentage_change, :change, :commission, :change_real_time, :after_hours_change_real_time, :dividend_share, :last_trade_date, :trade_date, :earnings_per_share, :eps_current_yr_estimate, :eps_next_yr_estimate, :eps_next_qtr_estimate, :day_low, :day_high, :year_low, :year_high, :market_cap, :market_cap_realtime, :ebitda, :change_from_year_low, :percentage_change_from_year_low, :last_trade_price, :day_range, :day_range_realtime, :fifty_day_mvg_avg, :two_hundred_day_mvg_avg, :change_from_two_hundred_day_mvg_avg, :percent_change_from_two_hundred_day_mvg_avg, :change_from_fifty_day_mvg_avg, :percent_change_from_fifty_day_mvg_avg, :name, :open, :previous_close, :ex_dividend_date, :per_ratio, :dividend_pay_date, :per_ratio_realtime, :peg_ratio, :price_eps_estimate_current_yr, :price_eps_estimate_next_yr, :short_ratio, :last_trade_time, :volume, :year_range, :day_value_change, :day_change_realtime, :stock_exchange, :dividend_yield, :percent_change

  def initialize(args)
    @symbol = args.fetch("symbol", nil)
    @ask = args.fetch("Ask", nil)
    @avg_daily_vol = args.fetch("AverageDailyVolume", nil)
    @bid = args.fetch("Bid", nil)
    @ask_real_time = args.fetch("AskRealtime", nil)
    @bid_real_time = args.fetch("BidRealtime", nil)
    @book_value = args.fetch("BookValue", nil)
    @change_percentage_change = args.fetch("Change_PercentChange", nil)
    @change = args.fetch("Change", nil)
    @commission = args.fetch("Commission", nil)
    @change_real_time = args.fetch("ChangeRealtime", nil)
    @after_hours_change_real_time = args.fetch("AfterHoursChangeRealtime", nil)
    @dividend_share = args.fetch("DividendShare", nil)
    @last_trade_date = args.fetch("LastTradeDate", nil)
    @trade_date = args.fetch("TradeDate", nil)
    @earnings_per_share = args.fetch("EarningsShare", nil)
    @eps_current_yr_estimate = args.fetch("EPSEstimateCurrentYear", nil)
    @eps_next_yr_estimate = args.fetch("EPSEstimateNextYear", nil)
    @eps_next_qtr_estimate = args.fetch("EPSEstimateNextQuarter", nil)
    @day_low = args.fetch("DaysLow", nil)
    @day_high = args.fetch("DaysHigh", nil)
    @year_low = args.fetch("YearLow", nil)
    @year_high = args.fetch("YearHigh", nil)
    @market_cap = args.fetch("MarketCapitalization", nil)
    @market_cap_realtime = args.fetch("MarketCapRealtime", nil)
    @ebitda = args.fetch("EBITDA", nil)
    @change_from_year_low = args.fetch("ChangeFromYearLow", nil)
    @percentage_change_from_year_low = args.fetch("PercentChangeFromYearLow", nil)
    @last_trade_price = args.fetch("LastTradePriceOnly", nil)
    @day_range = args.fetch("DaysRange", nil)
    @day_range_realtime = args.fetch("DaysRangeRealtime", nil)
    @fifty_day_mvg_avg = args.fetch("FiftydayMovingAverage", nil)
    @two_hundred_day_mvg_avg = args.fetch("TwoHundreddayMovingAverage", nil)
    @change_from_two_hundred_day_mvg_avg = args.fetch("ChangeFromTwoHundreddayMovingAverage", nil)
    @percent_change_from_two_hundred_day_mvg_avg = args.fetch("PercentChangeFromTwoHundreddayMovingAverage", nil)
    @change_from_fifty_day_mvg_avg = args.fetch("ChangeFromFiftydayMovingAverage", nil)
    @percent_change_from_fifty_day_mvg_avg = args.fetch("PercentChangeFromFiftydayMovingAverage", nil)
    @name = args.fetch("Name", nil)
    @open = args.fetch("Open", nil)
    @previous_close = args.fetch("PreviousClose", nil)
    @ex_dividend_date = args.fetch("ExDividendDate", nil)
    @per_ratio = args.fetch("PERatio", nil)
    @dividend_pay_date = args.fetch("DividendPayDate", nil)
    @per_ratio_realtime = args.fetch("PERatioRealtime", nil)
    @peg_ratio = args.fetch("PEGRatio", nil)
    @price_eps_estimate_current_yr = args.fetch("PriceEPSEstimateCurrentYear", nil)
    @price_eps_estimate_next_yr = args.fetch("PriceEPSEstimateNextYear", nil)
    @short_ratio = args.fetch("ShortRatio", nil)
    @last_trade_time = args.fetch("LastTradeTime", nil)
    @volume = args.fetch("Volume", nil)
    @year_range = args.fetch("YearRange", nil)
    @day_value_change = args.fetch("DaysValueChange", nil)
    @day_change_realtime = args.fetch("DaysValueChangeRealtime", nil)
    @stock_exchange = args.fetch("StockExchange", nil)
    @dividend_yield = args.fetch("DividendYield", nil)
    @percent_change = args.fetch("PercentChange", nil)
  end
end
